# Generated by Django 4.1 on 2022-10-21 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mustahdimin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarihce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('current_os', models.CharField(blank=True, max_length=124, null=True)),
                ('current_os_version', models.CharField(blank=True, max_length=124, null=True)),
                ('current_browser', models.CharField(blank=True, max_length=124, null=True)),
                ('current_browser_version', models.CharField(blank=True, max_length=124, null=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('mustahdim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
