# Generated by Django 4.1 on 2022-10-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesanid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonelik',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='ArgeGiderleri',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Banka',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='Cek',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='Herkobi',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='Iade',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Ihracat',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Iskonto',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Kasa',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.hesab',),
        ),
        migrations.CreateModel(
            name='PazarlamaGiderleri',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Satici',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Shm',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='Stmm',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='TicariMal',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='YonetimGiderleri',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
        migrations.CreateModel(
            name='YurticiSatis',
            fields=[
            ],
            options={
                'ordering': ('isim',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mesanid.stok',),
        ),
    ]
