# Generated by Django 4.1 on 2022-10-22 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mustecirin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fihrist',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tadilat_tarihi', models.DateTimeField(auto_now=True)),
                ('isim', models.CharField(max_length=255, verbose_name='Uygulama İsimi')),
                ('sebike', models.SlugField(blank=True, null=True, unique=True)),
                ('kufl', models.IntegerField(unique=True)),
                ('faaldir', models.BooleanField(default=False)),
                ('borc', models.DecimalField(decimal_places=2, default=0, help_text='max 9999999,99', max_digits=9, verbose_name='Borç')),
                ('alacak', models.DecimalField(decimal_places=2, default=0, help_text='max 9999999,99', max_digits=9, verbose_name='Alacak')),
                ('mustecir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mustecirin.mustecir')),
            ],
            options={
                'verbose_name': 'Etkin Uygulama',
                'verbose_name_plural': 'Etkin Uygulamalar',
            },
        ),
        migrations.CreateModel(
            name='Hesab',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tadilat_tarihi', models.DateTimeField(auto_now=True)),
                ('isim', models.CharField(max_length=255, verbose_name='İsim')),
                ('kufl', models.IntegerField()),
                ('borc', models.DecimalField(decimal_places=2, default=0, help_text='max 9999999,99', max_digits=9, verbose_name='Borç')),
                ('alacak', models.DecimalField(decimal_places=2, default=0, help_text='max 9999999,99', max_digits=9, verbose_name='Alacak')),
                ('fihrist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesanid.fihrist')),
                ('mustecir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mustecirin.mustecir')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('hesab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mesanid.hesab')),
                ('giren', models.IntegerField(default=0)),
                ('cikan', models.IntegerField(default=0)),
                ('faaldir', models.BooleanField(default=False)),
                ('kdv_orani', models.IntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
            bases=('mesanid.hesab',),
            managers=[
                ('stoklar', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tadilat_tarihi', models.DateTimeField(auto_now=True)),
                ('isim', models.CharField(max_length=255, verbose_name='İsim')),
                ('giren', models.IntegerField(default=0)),
                ('cikan', models.IntegerField(default=0)),
                ('faaldir', models.BooleanField(default=False)),
                ('stok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesanid.stok')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
