# Generated by Django 4.1 on 2022-10-21 21:11

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tatbik',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tadilat_tarihi', models.DateTimeField(auto_now=True)),
                ('isim', models.CharField(max_length=255)),
                ('meshur_isim', models.CharField(blank=True, max_length=255, null=True)),
                ('sebike', models.SlugField(blank=True, null=True, unique=True)),
                ('teallukat', models.CharField(blank=True, max_length=255, null=True)),
                ('miftah', models.IntegerField()),
                ('faaldir', models.BooleanField(default=False)),
                ('fiyat', models.DecimalField(decimal_places=2, default=10, help_text='max 9999999,99', max_digits=9, verbose_name='Fiyat')),
            ],
            options={
                'verbose_name_plural': 'Uygulamalar',
                'ordering': ['miftah'],
            },
        ),
        migrations.CreateModel(
            name='Mustecir',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tadilat_tarihi', models.DateTimeField(auto_now=True)),
                ('unvan', models.CharField(max_length=250, verbose_name='Unvan')),
                ('ad', models.CharField(blank=True, max_length=124, null=True, verbose_name='Ad')),
                ('soyad', models.CharField(blank=True, max_length=124, null=True, verbose_name='Soyad')),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(default='+901234567899', max_length=30, region=None, verbose_name='telefon')),
                ('adres', models.TextField(blank=True, null=True)),
                ('vergi_dairesi', models.CharField(blank=True, max_length=124, null=True)),
                ('vergi_numarasi', models.CharField(blank=True, max_length=124, null=True)),
                ('il', models.CharField(blank=True, max_length=124, null=True)),
                ('ilce', models.CharField(blank=True, max_length=124, null=True)),
                ('ulke', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('sebike', models.SlugField(blank=True, null=True)),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Eposta Adresi')),
                ('mumtaz', models.BooleanField(default=False)),
                ('resim_url', models.ImageField(blank=True, default='images/default.png', help_text='format: zorunlu, default-default.png', null=True, upload_to='images/', verbose_name="Resim URL'si")),
                ('tatbikat', models.ManyToManyField(blank=True, to='mustecirin.tatbik')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
